spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:finances_test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
  h2:
    console:
      enable: true
      path: /h2

keycloak:
  realm: test
  host: http://test:8443